name: diff

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Web-Dev-For-Beginners

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3.1.2
        
      - name: checkout to result branch
        run : git checkout -b result
         
      - name: cloning repository
        run : git clone https://github.com/devrel-kr/Web-Dev-For-Beginners.git
          
      - name: add upstream
        run : git remote add upstream https://github.com/microsoft/Web-Dev-For-Beginners.git
        working-directory: ${{ env.working-directory }}
      
      - name: check repository
        run : git remote -v
        working-directory: ${{ env.working-directory }}

      - name: fetch upstream
        run : git fetch upstream
        working-directory: ${{ env.working-directory }}
        
      - name: checkout to upstream
        run : git checkout upstream/main
        working-directory: ${{ env.working-directory }}
        
      - name: copy python script
        run : cp diff_i18n.py ${{ env.working-directory }}
        
      - name: run python script
        run : python diff_i18n.py main upstream/main
        working-directory: ${{ env.working-directory }}
      
      - name: make report dir
        run : mkdir report
        
      - name: copy result
        run : mkdir report && cp report_tree.md ../report
        working-directory: ${{ env.working-directory }}
        
      - name: Set config
        run : |
          git config --global user.email "kwang1406@gmail.com"
          git config --global user.name "evartuna"
          git config --global core.autocrlf true
      - name: push to github
        run : |
          git add report/*.md
          git commit -m "Add report"
          
      - name: Push to report
        run: git push origin result
